//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by cm.rc
//
#define IDS_TB_CONNECT                  1
#define IDS_TB_DISCONNECT               2
#define IDS_TB_QUICK_CONNECT            3
#define IDS_TB_SHORTCUT                 4
#define IDS_TB_NEW                      5
#define IDS_TB_COPY                     6
#define IDS_TB_PROPERTIES               7
#define IDS_TB_DELETE                   8
#define IDS_COL_NAME                    9
#define IDS_COL_DESCRIPTION             10
#define IDS_COL_TARGET                  11
#define IDS_ABOUT_BUILD_FMT             12
#define IDS_ABOUT_VER_FMT               14
#define IDS_ABOUT_VER_FOR_NT            15
#define IDS_COL_ID                      16
#define IDS_COL_START_TIME              17
#define IDS_COL_ELAPSED_TIME            18
#define IDC_STATUSBAR                   101
#define IDR_MENU                        103
#define IDD_GENERAL                     107
#define IDD_CONNECTION                  108
#define IDD_CONNECTION_IP               108
#define IDD_TERMINAL                    109
#define IDD_TRANSFER                    110
#define IDD_TELNET                      111
#define IDD_FTP                         112
#define IDD_TCPIP                       113
#define IDD_TLS                         114
#define IDD_KEYBOARD                    115
#define IDD_LOGIN                       116
#define IDR_TOOLBAR1                    116
#define IDD_PRINTER                     117
#define IDD_TERM_COLORS                 118
#define IDD_GUI                         119
#define IDD_GUI_COLORS                  120
#define IDD_LOGGING                     121
#define IDD_ABOUT                       122
#define IDB_BITMAP1                     125
#define IDR_ACCELERATOR1                127
#define IDI_LOGO                        128
#define IDR_CONTEXT_MENU                131
#define IDD_NEW_CONNECTION              132
#define IDD_DISCONNECT_SESSION          135
#define IDD_CONNECTION_BASIC            136
#define IDD_CONNECTION_CMD              137
#define IDD_CONNECTION_SERIAL           138
#define IDC_NAME                        1000
#define IDC_GENERAL_NAME                1000
#define IDC_DESCRIPTION                 1001
#define IDC_GENERAL_DESCRIPTION         1001
#define IDC_TEMPLATE                    1002
#define IDC_NOTES                       1003
#define IDC_GENERAL_NOTES               1003
#define IDC_CONECTION_TYPE              1006
#define IDC_EDIT1                       1007
#define IDC_EDIT2                       1008
#define IDC_COMBO2                      1009
#define IDC_EDIT14                      1009
#define IDC_CHECK1                      1010
#define IDC_EDIT17                      1010
#define IDC_LIST1                       1011
#define IDC_EDIT20                      1011
#define IDC_RADIO1                      1012
#define IDC_EDIT23                      1012
#define IDC_RADIO2                      1013
#define IDC_EDIT26                      1013
#define IDC_EDIT29                      1014
#define IDC_COMBO1                      1015
#define IDC_EDIT32                      1015
#define IDC_SPIN2                       1016
#define IDC_EDIT35                      1016
#define IDC_COMBO3                      1017
#define IDC_EDIT38                      1017
#define IDC_CHECK2                      1018
#define IDC_EDIT41                      1018
#define IDC_CHECK3                      1019
#define IDC_EDIT44                      1019
#define IDC_CHECK4                      1020
#define IDC_EDIT47                      1020
#define IDC_COMBO4                      1021
#define IDC_EDIT50                      1021
#define IDC_SPIN1                       1022
#define IDC_EDIT53                      1022
#define IDC_RADIO3                      1023
#define IDC_RADIO4                      1024
#define IDC_RADIO5                      1025
#define IDC_RADIO6                      1026
#define IDC_RADIO7                      1027
#define IDC_RADIO8                      1028
#define IDC_EDIT3                       1029
#define IDC_BUTTON1                     1030
#define IDC_EDIT7                       1030
#define IDC_COMBO5                      1031
#define IDC_COMBO6                      1032
#define IDC_CHECK5                      1033
#define IDC_CHECK6                      1034
#define IDC_CHECK7                      1035
#define IDC_CHECK8                      1036
#define IDC_COMBO7                      1037
#define IDC_EDIT4                       1038
#define IDC_EDIT5                       1039
#define IDC_EDIT6                       1040
#define IDC_CHECK9                      1041
#define IDC_EDIT8                       1041
#define IDC_CHECK10                     1042
#define IDC_EDIT9                       1042
#define IDC_EDIT10                      1043
#define IDC_BUTTON2                     1043
#define IDC_BUTTON3                     1044
#define IDC_EDIT12                      1044
#define IDC_BUTTON4                     1045
#define IDC_EDIT15                      1045
#define IDC_RADIO9                      1046
#define IDC_EDIT18                      1046
#define IDC_RADIO10                     1047
#define IDC_EDIT21                      1047
#define IDC_EDIT24                      1048
#define IDC_COMBO8                      1049
#define IDC_EDIT27                      1049
#define IDC_COL_STAT_BG                 1049
#define IDC_COMBO9                      1050
#define IDC_EDIT30                      1050
#define IDC_COL_MOU_BG                  1050
#define IDC_COMBO10                     1051
#define IDC_EDIT33                      1051
#define IDC_COL_POP_BG                  1051
#define IDC_COMBO11                     1052
#define IDC_EDIT36                      1052
#define IDC_COL_UL_FG                   1052
#define IDC_COMBO12                     1053
#define IDC_EDIT39                      1053
#define IDC_BUTTON5                     1053
#define IDC_COL_UL_BG                   1053
#define IDC_SPIN3                       1054
#define IDC_EDIT42                      1054
#define IDC_BUTTON6                     1054
#define IDC_EDIT11                      1055
#define IDC_BUTTON7                     1055
#define IDC_EDIT13                      1056
#define IDC_CHECK11                     1056
#define IDC_EDIT16                      1057
#define IDC_CHECK12                     1057
#define IDC_EDIT19                      1058
#define IDC_CHECK13                     1058
#define IDC_EDIT22                      1059
#define IDC_CHECK14                     1059
#define IDC_EDIT25                      1060
#define IDC_CHECK15                     1060
#define IDC_EDIT28                      1061
#define IDC_BUTTON8                     1061
#define IDC_EDIT31                      1062
#define IDC_CHECK16                     1062
#define IDC_EDIT34                      1063
#define IDC_CHECK17                     1063
#define IDC_EDIT37                      1064
#define IDC_CHECK18                     1064
#define IDC_EDIT40                      1065
#define IDC_CHECK19                     1065
#define IDC_EDIT43                      1066
#define IDC_CHECK20                     1066
#define IDC_EDIT45                      1067
#define IDC_CHECK21                     1067
#define IDC_EDIT46                      1068
#define IDC_EDIT48                      1069
#define IDC_EDIT49                      1070
#define IDC_LIST3                       1070
#define IDC_EDIT51                      1071
#define IDC_EDIT52                      1072
#define IDC_NEW_CONN_NAME               1072
#define IDC_EDIT54                      1073
#define IDC_NEW_CONN_HOSTNAME           1073
#define IDC_EDIT55                      1074
#define IDC_NEW_CONN_PORT               1074
#define IDC_NEW_CONN_OTHER              1075
#define IDC_NEW_CONN_SSH                1077
#define IDC_NEW_CONN_SERIAL             1078
#define IDC_NEW_CONN_FTP                1079
#define IDC_NEW_CONN_IP                 1080
#define IDC_NEW_CONN_SER_PORT           1082
#define IDC_NEW_CONN_SPEED              1083
#define IDC_NEW_CONN_TARGET             1084
#define IDC_NEW_CONN_PARAMETER          1085
#define IDC_NEW_CONN_OPEN_PROPS         1088
#define IDC_NEW_CONN_NAMED_PIPE         1089
#define IDC_NEW_CONN_PTY                1090
#define IDC_ABOUT_BUILD                 1091
#define IDC_ABOUT_VERSION               1092
#define IDC_GENERAL_DOWNLOAD            1093
#define IDC_GENERAL_START               1094
#define IDC_DISCONNECT_LIST             1097
#define IDC_DISCONNECT_ALL              1098
#define IDC_TERM_TYPE                   1099
#define IDC_TERM_WIDTH                  1100
#define IDC_TERM_HEIGHT                 1101
#define IDC_TERM_SCROLLBACK             1102
#define IDC_TERM_CURSOR                 1104
#define IDC_TERM_CSET                   1105
#define IDC_TERM_BITS_7                 1106
#define IDC_TERM_BITS_8                 1107
#define IDC_TERM_LOCAL_ECHO             1108
#define IDC_TERM_AUTO_WRAP              1109
#define IDC_TERM_APC                    1110
#define IDC_TERM_STATUS_LINE            1111
#define IDC_TERM_COLOR_DEFAULTS         1112
#define IDC_COL_TERM_FG                 1113
#define IDC_COL_TERM_BG                 1114
#define IDC_COL_COMM_FG                 1115
#define IDC_COL_COMM_BG                 1116
#define IDC_COL_STAT_FG                 1117
#define IDC_COL_MOU_FG                  1118
#define IDC_COL_POP_FG                  1119
#define IDC_LOGIN_USER                  1120
#define IDC_LOGIN_PASS                  1121
#define IDC_LOGIN_PROMPT                1122
#define IDC_LOGIN_RUN_FILE              1123
#define IDC_LOGIN_FILENAME              1124
#define IDC_LOGIN_BROWSE                1125
#define IDC_LOGIN_SCRIPT                1126
#define IDC_CONN_HOSTNAME               1127
#define IDC_CONN_PROTO                  1129
#define IDC_CONN_PORT                   1130
#define IDC_CONN_EXIT_ON_DISCON         1131
#define IDC_CONN_PARAM_A_LBL            1132
#define IDC_CONN_PARAM_A                1133
#define IDC_CONN_PARAM_B_LBL            1134
#define IDC_CONN_PARAM_B                1135
#define IDC_CONN_LINE                   1136
#define IDC_CONN_SPEED                  1137
#define IDC_CONN_FLOW                   1138
#define IDC_CONN_PARITY                 1139
#define IDC_CONN_STOP                   1140
#define IDC_CONN_ERROR_CORRECTION       1141
#define IDC_CONN_DATA_COMPRESSION       1142
#define IDC_CONN_CARRIER_DETECT         1143
#define IDC_KBD_BS_DELETE               1144
#define IDC_KBD_BS_BS                   1145
#define IDC_KBD_BS_CTRL_Y               1146
#define IDC_KBD_RET_CR                  1147
#define IDC_KBD_RET_CRLF                1148
#define IDC_KBD_RET_LF                  1149
#define IDC_MOU_ON                      1150
#define IDC_MOU_OFF                     1151
#define IDC_KBD_KM_FILENAME             1152
#define IDC_KBD_KM_KEYMAP               1153
#define IDC_KBD_KM_FILE_BROWSE          1154
#define ID_FILE_EXIT                    40001
#define ID_TEST_GO                      40002
#define ID_TEST_GOMODELESS              40003
#define ID_TB_CONNECT                   40004
#define ID_TB_DISCONNECT                40005
#define ID_TB_QUICK_CONNECT             40006
#define ID_TB_SHORTCUT                  40007
#define ID_TB_NEW                       40008
#define ID_TB_DELETE                    40009
#define ID_TB_COPY                      40010
#define ID_TB_PROPERTIES                40011
#define ID_FILE_EXPORTCONNECTIONS       40014
#define ID_CONNECTION_ADD               40015
#define ID_CONNECTION_CLONE             40016
#define ID_CONNECTION_DELETE            40017
#define ID_CONNECTION_PROPERTIES        40018
#define ID_CONNECTION_CONNECT           40019
#define ID_OPTIONS_MINIMIZEONCONNECT    40020
#define ID_HELP_ABOUT                   40023
#define ID_FILE_IMPORTCONNECTIONS       40024
#define ID_CONNECTION_DISCONNECT        40025
#define ID_CONNECTION_SHORTCUT          40026
#define ID_CONTEXT_CONNECT              40028
#define ID_CONTEXT_CREATESHORTCUT       40029
#define ID_CONTEXT_DELETE               40030
#define ID_CONTEXT_PROPERTIES           40031
#define ID_CONTEXT_CLONE                40032
#define ID_CONTEXT_ADD                  40033
#define ID_CONTEXT_DISCONNECT           40034
#define ID_CONTEXT_CREATESCRIPT         40035
#define ID_CONNECTION_CREATESCRIPT      40036

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        136
#define _APS_NEXT_COMMAND_VALUE         40037
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
