@if exist *.dll del *.dll
@if exist *.exp del *.exp
@if exist *.ilk del *.ilk
@if exist *.lib del *.lib
@if exist *.map del *.map
@if exist *.pdb del *.pdb
@if exist *.obj del *.obj
@if exist *.err del *.err
@if exist *.res del *.res